added checks for yad, xclip and default config directory

diff --git a/boardclip b/boardclip
--- a/boardclip
+++ b/boardclip
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 check_yad() {
+  # 'yad' must be installed or in PATH. Otherwise abort.
   if ! which yad >/dev/null
   then
     echo "'yad' not found!"
@@ -10,6 +11,7 @@ check_yad() {
 }
 
 check_xclip() {
+  # 'xclip' must be installed or in PATH. Otherwise abort.
   if ! which xclip >/dev/null
   then
     echo "'xclip' not found!"
@@ -18,9 +20,22 @@ check_xclip() {
   fi
 }
 
-#check_cfg_dir() {
-#  
-#}
+check_cfg_dir() {
+  # If the default directory is not present, create it. Exit if something goes wrong.
+  if ! test -d $BOARDCLIP_DIR
+  then
+    echo "Default directory not found!"
+    echo -n "Creating it under '$BOARDCLIP_DIR' => "
+    if mkdir $BOARDCLIP_DIR
+    then
+      echo "Done!"
+    else
+      echo "ERROR"
+      exit 1
+    fi
+  fi
+}
+
 BOARDCLIP_DIR=~/.config/Boardclip
 BOARDCLIP_CFG=$BOARDCLIP_DIR/config
 source $BOARDCLIP_CFG
